
services:
  osmdbutils:
    image: osmdbutils
    build:
      context: ./src
    container_name: osm-db-utils
    hostname: osmdbutils
    mem_limit: 96g
    restart: "no"
    command: run
    volumes:
      - /media/data2/openstreetmap-flat-nodes:/nodes
      - /media/data2/openstreetmap-db:/var/lib/postgresql/11/main:ro
      - ./volumes/transfer:/transfer
      - ./volumes/work:/replication/work
      - /media/data2/openstreetmap-downloads:/replication/download
      - ./volumes/backup:/backup
    networks:
      - tile-postgis-network

networks:
  tile-postgis-network:
    external: true
  
# docker network create tile-postgis-network